//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RottenTomatoesViewer.Web.MovieTheaterInfo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Theater", Namespace="http://www.ignyte.com/whatsshowing")]
    [System.SerializableAttribute()]
    public partial class Theater : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RottenTomatoesViewer.Web.MovieTheaterInfo.Movie[] MoviesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public RottenTomatoesViewer.Web.MovieTheaterInfo.Movie[] Movies {
            get {
                return this.MoviesField;
            }
            set {
                if ((object.ReferenceEquals(this.MoviesField, value) != true)) {
                    this.MoviesField = value;
                    this.RaisePropertyChanged("Movies");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://www.ignyte.com/whatsshowing")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RunningTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShowTimesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingField, value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RunningTime {
            get {
                return this.RunningTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RunningTimeField, value) != true)) {
                    this.RunningTimeField = value;
                    this.RaisePropertyChanged("RunningTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ShowTimes {
            get {
                return this.ShowTimesField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowTimesField, value) != true)) {
                    this.ShowTimesField = value;
                    this.RaisePropertyChanged("ShowTimes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpcomingMovie", Namespace="http://www.ignyte.com/whatsshowing")]
    [System.SerializableAttribute()]
    public partial class UpcomingMovie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MovieName {
            get {
                return this.MovieNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieNameField, value) != true)) {
                    this.MovieNameField = value;
                    this.RaisePropertyChanged("MovieName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ignyte.com/whatsshowing", ConfigurationName="MovieTheaterInfo.MovieInformationSoap")]
    public interface MovieInformationSoap {
        
        // CODEGEN: Generating message contract since element name zipCode from namespace http://www.ignyte.com/whatsshowing is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ignyte.com/whatsshowing/GetTheatersAndMovies", ReplyAction="*")]
        RottenTomatoesViewer.Web.MovieTheaterInfo.GetTheatersAndMoviesResponse GetTheatersAndMovies(RottenTomatoesViewer.Web.MovieTheaterInfo.GetTheatersAndMoviesRequest request);
        
        // CODEGEN: Generating message contract since element name GetUpcomingMoviesResult from namespace http://www.ignyte.com/whatsshowing is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ignyte.com/whatsshowing/GetUpcomingMovies", ReplyAction="*")]
        RottenTomatoesViewer.Web.MovieTheaterInfo.GetUpcomingMoviesResponse GetUpcomingMovies(RottenTomatoesViewer.Web.MovieTheaterInfo.GetUpcomingMoviesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTheatersAndMoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTheatersAndMovies", Namespace="http://www.ignyte.com/whatsshowing", Order=0)]
        public RottenTomatoesViewer.Web.MovieTheaterInfo.GetTheatersAndMoviesRequestBody Body;
        
        public GetTheatersAndMoviesRequest() {
        }
        
        public GetTheatersAndMoviesRequest(RottenTomatoesViewer.Web.MovieTheaterInfo.GetTheatersAndMoviesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ignyte.com/whatsshowing")]
    public partial class GetTheatersAndMoviesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string zipCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int radius;
        
        public GetTheatersAndMoviesRequestBody() {
        }
        
        public GetTheatersAndMoviesRequestBody(string zipCode, int radius) {
            this.zipCode = zipCode;
            this.radius = radius;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTheatersAndMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTheatersAndMoviesResponse", Namespace="http://www.ignyte.com/whatsshowing", Order=0)]
        public RottenTomatoesViewer.Web.MovieTheaterInfo.GetTheatersAndMoviesResponseBody Body;
        
        public GetTheatersAndMoviesResponse() {
        }
        
        public GetTheatersAndMoviesResponse(RottenTomatoesViewer.Web.MovieTheaterInfo.GetTheatersAndMoviesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ignyte.com/whatsshowing")]
    public partial class GetTheatersAndMoviesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RottenTomatoesViewer.Web.MovieTheaterInfo.Theater[] GetTheatersAndMoviesResult;
        
        public GetTheatersAndMoviesResponseBody() {
        }
        
        public GetTheatersAndMoviesResponseBody(RottenTomatoesViewer.Web.MovieTheaterInfo.Theater[] GetTheatersAndMoviesResult) {
            this.GetTheatersAndMoviesResult = GetTheatersAndMoviesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpcomingMoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpcomingMovies", Namespace="http://www.ignyte.com/whatsshowing", Order=0)]
        public RottenTomatoesViewer.Web.MovieTheaterInfo.GetUpcomingMoviesRequestBody Body;
        
        public GetUpcomingMoviesRequest() {
        }
        
        public GetUpcomingMoviesRequest(RottenTomatoesViewer.Web.MovieTheaterInfo.GetUpcomingMoviesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ignyte.com/whatsshowing")]
    public partial class GetUpcomingMoviesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int month;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int year;
        
        public GetUpcomingMoviesRequestBody() {
        }
        
        public GetUpcomingMoviesRequestBody(int month, int year) {
            this.month = month;
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpcomingMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpcomingMoviesResponse", Namespace="http://www.ignyte.com/whatsshowing", Order=0)]
        public RottenTomatoesViewer.Web.MovieTheaterInfo.GetUpcomingMoviesResponseBody Body;
        
        public GetUpcomingMoviesResponse() {
        }
        
        public GetUpcomingMoviesResponse(RottenTomatoesViewer.Web.MovieTheaterInfo.GetUpcomingMoviesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ignyte.com/whatsshowing")]
    public partial class GetUpcomingMoviesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RottenTomatoesViewer.Web.MovieTheaterInfo.UpcomingMovie[] GetUpcomingMoviesResult;
        
        public GetUpcomingMoviesResponseBody() {
        }
        
        public GetUpcomingMoviesResponseBody(RottenTomatoesViewer.Web.MovieTheaterInfo.UpcomingMovie[] GetUpcomingMoviesResult) {
            this.GetUpcomingMoviesResult = GetUpcomingMoviesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MovieInformationSoapChannel : RottenTomatoesViewer.Web.MovieTheaterInfo.MovieInformationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovieInformationSoapClient : System.ServiceModel.ClientBase<RottenTomatoesViewer.Web.MovieTheaterInfo.MovieInformationSoap>, RottenTomatoesViewer.Web.MovieTheaterInfo.MovieInformationSoap {
        
        public MovieInformationSoapClient() {
        }
        
        public MovieInformationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovieInformationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieInformationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieInformationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RottenTomatoesViewer.Web.MovieTheaterInfo.GetTheatersAndMoviesResponse RottenTomatoesViewer.Web.MovieTheaterInfo.MovieInformationSoap.GetTheatersAndMovies(RottenTomatoesViewer.Web.MovieTheaterInfo.GetTheatersAndMoviesRequest request) {
            return base.Channel.GetTheatersAndMovies(request);
        }
        
        public RottenTomatoesViewer.Web.MovieTheaterInfo.Theater[] GetTheatersAndMovies(string zipCode, int radius) {
            RottenTomatoesViewer.Web.MovieTheaterInfo.GetTheatersAndMoviesRequest inValue = new RottenTomatoesViewer.Web.MovieTheaterInfo.GetTheatersAndMoviesRequest();
            inValue.Body = new RottenTomatoesViewer.Web.MovieTheaterInfo.GetTheatersAndMoviesRequestBody();
            inValue.Body.zipCode = zipCode;
            inValue.Body.radius = radius;
            RottenTomatoesViewer.Web.MovieTheaterInfo.GetTheatersAndMoviesResponse retVal = ((RottenTomatoesViewer.Web.MovieTheaterInfo.MovieInformationSoap)(this)).GetTheatersAndMovies(inValue);
            return retVal.Body.GetTheatersAndMoviesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RottenTomatoesViewer.Web.MovieTheaterInfo.GetUpcomingMoviesResponse RottenTomatoesViewer.Web.MovieTheaterInfo.MovieInformationSoap.GetUpcomingMovies(RottenTomatoesViewer.Web.MovieTheaterInfo.GetUpcomingMoviesRequest request) {
            return base.Channel.GetUpcomingMovies(request);
        }
        
        public RottenTomatoesViewer.Web.MovieTheaterInfo.UpcomingMovie[] GetUpcomingMovies(int month, int year) {
            RottenTomatoesViewer.Web.MovieTheaterInfo.GetUpcomingMoviesRequest inValue = new RottenTomatoesViewer.Web.MovieTheaterInfo.GetUpcomingMoviesRequest();
            inValue.Body = new RottenTomatoesViewer.Web.MovieTheaterInfo.GetUpcomingMoviesRequestBody();
            inValue.Body.month = month;
            inValue.Body.year = year;
            RottenTomatoesViewer.Web.MovieTheaterInfo.GetUpcomingMoviesResponse retVal = ((RottenTomatoesViewer.Web.MovieTheaterInfo.MovieInformationSoap)(this)).GetUpcomingMovies(inValue);
            return retVal.Body.GetUpcomingMoviesResult;
        }
    }
}
